### ISSUE TITLE
missing function  toThrow()

### ISSUE THREAD

**Issue by GeorgGerber** [ValeriaVG/tiny-jest#1]
The idea for a tiny jest-like module is great, I want to use it. But an important function of jest is 
expect(....).toThrow()
in order to check usecases, in wich the testee runs into an exception.

**Comment by ValeriaVG** [comment]
I agree, @GeorgGerber , this is an essential part and should definitely be added to the package.
Do you think it'll be sufficient for now to cover the following use cases?

```js
expect(someFunction).toThrow()
expect(someFunction).toThrow(/^Regular Expression/)
```
